project_name: live-streamer
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ldflags:
      - -s -w -X live-streamer/constant.Version={{ .Version }}
    flags:
      - -trimpath
archives:
  - format: tar.gz
    format_overrides:
      - format: zip
        goos: windows
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
release:
  draft: true
upx:
  - enabled: true
    compress: best
